version: 1.0.{build}
build_script:
  - ps: .\buildUmbracoCms.ps1
notifications:
- provider: Email
  to:
  - christianthillemann@gmail.com
  subject: appVeyor build
  message: "Mojn kedde\n\nDer er forsøgt en kørsel af kedde.umbraco.tests.dll på appVeyor"
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true