version: 1.0.{build}
environment:
  access_token:
    secure: cRHKcG0F5Dr7Mgf8t5z8p5BQF9Bt6gegCtm2uzvwZ39RQ2fjC0n3KImyNx/SdCvX
build_script:
  - ps: .\buildUmbracoCms.ps1
test: off
deploy:
deploy:
- provider: NuGet
  server: https://www.nuget.org/api/v2/package
  api_key:
    secure: qsYLcD3EOYOLIvCNAoqewbIu50P7F0BUmF6RnOK35z1wrTZbmTw+D5DPG+Y/EKvM
  artifact: '*.nupkg'
- provider: NuGet
  server: https://www.myget.org/F/umbraco-packages/
  api_key:
    secure: rDRFa13qnNBv4tehvJuw/lr/rYB0iLfVepQMQPYInOjria+LTV01ij1GUIz7mIki
  artifact: '*.nupkg'
on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "christianthillemann@gmail.com"
  - git config --global user.name "kedde"
  - git status
  - git diff
  - git diff-index --quiet HEAD || git commit -am "updated nuspec version"
  - git push origin HEAD:master